// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace URSpot.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("URSpot.Core.Resources.CommonResources", typeof(CommonResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MenuFavourites {
            get {
                return ResourceManager.GetString("MenuFavourites", resourceCulture);
            }
        }
        
        internal static string MenuFriends {
            get {
                return ResourceManager.GetString("MenuFriends", resourceCulture);
            }
        }
        
        internal static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        internal static string MenuProfile {
            get {
                return ResourceManager.GetString("MenuProfile", resourceCulture);
            }
        }
        
        internal static string MenuSignIn {
            get {
                return ResourceManager.GetString("MenuSignIn", resourceCulture);
            }
        }
        
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        internal static string GenderMale {
            get {
                return ResourceManager.GetString("GenderMale", resourceCulture);
            }
        }
        
        internal static string GenderFemale {
            get {
                return ResourceManager.GetString("GenderFemale", resourceCulture);
            }
        }
        
        internal static string GenderCustom {
            get {
                return ResourceManager.GetString("GenderCustom", resourceCulture);
            }
        }
        
        internal static string LocationMessage {
            get {
                return ResourceManager.GetString("LocationMessage", resourceCulture);
            }
        }
        
        internal static string AnswerYes {
            get {
                return ResourceManager.GetString("AnswerYes", resourceCulture);
            }
        }
        
        internal static string AnswerNo {
            get {
                return ResourceManager.GetString("AnswerNo", resourceCulture);
            }
        }
        
        internal static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        internal static string BugPlaceHolder {
            get {
                return ResourceManager.GetString("BugPlaceHolder", resourceCulture);
            }
        }
        
        internal static string LabelTextProfile {
            get {
                return ResourceManager.GetString("LabelTextProfile", resourceCulture);
            }
        }
        
        internal static string LabelTextSocialNetworks {
            get {
                return ResourceManager.GetString("LabelTextSocialNetworks", resourceCulture);
            }
        }
        
        internal static string LabelTextPayment {
            get {
                return ResourceManager.GetString("LabelTextPayment", resourceCulture);
            }
        }
        
        internal static string LabelTextRewards {
            get {
                return ResourceManager.GetString("LabelTextRewards", resourceCulture);
            }
        }
        
        internal static string LabelTextInviteFriend {
            get {
                return ResourceManager.GetString("LabelTextInviteFriend", resourceCulture);
            }
        }
        
        internal static string LabelTextPromotion {
            get {
                return ResourceManager.GetString("LabelTextPromotion", resourceCulture);
            }
        }
        
        internal static string LabelTextAboutApp {
            get {
                return ResourceManager.GetString("LabelTextAboutApp", resourceCulture);
            }
        }
        
        internal static string LabelTextSignout {
            get {
                return ResourceManager.GetString("LabelTextSignout", resourceCulture);
            }
        }
    }
}
